name: Daily HN Summary

# on:
#   schedule:
#     # Run at 8:00 UTC (adjust as needed)
#     - cron: "0 23 * * *"

#   # Allow manual triggering
#   workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Secrets
        run: |
          echo "Checking if secrets are available..."
          if [ -n "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "GEMINI_API_KEY is set"
          else
            echo "GEMINI_API_KEY is NOT set"
          fi

          if [ -n "${{ secrets.EMAIL_USERNAME }}" ]; then
            echo "EMAIL_USERNAME is set"
          else
            echo "EMAIL_USERNAME is NOT set"
          fi

          if [ -n "${{ secrets.EMAIL_SENDER }}" ]; then
            echo "EMAIL_SENDER is set"
          else
            echo "EMAIL_SENDER is NOT set"
          fi

          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "SLACK_WEBHOOK_URL is set"
          else
            echo "SLACK_WEBHOOK_URL is NOT set"
          fi

      - name: Run HN Summarizer
        env:
          # LLM API keys
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          # Delivery credentials
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: |
          echo "Environment variables check:"
          if [ -n "$GEMINI_API_KEY" ]; then
            echo "GEMINI_API_KEY environment variable is set"
          else
            echo "GEMINI_API_KEY environment variable is NOT set"
          fi

          if [ -n "$EMAIL_SENDER" ]; then
            echo "EMAIL_SENDER environment variable is set"
          else
            echo "EMAIL_SENDER environment variable is NOT set"
          fi

          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            echo "SLACK_WEBHOOK_URL environment variable is set"
          else
            echo "SLACK_WEBHOOK_URL environment variable is NOT set"
          fi

          python src/main.py --config config.yaml --debug
